// Automatically generated by UaaLPluginGenerator
// If interface name was modifyed/removed you will need to fix this manually
// if you having compile issues COMMENT NEXT LINE

#define USE_INTERFACES

using UnityEngine;
using System.Runtime.InteropServices;

public partial class UaaLPlugin : MonoBehaviour
{
	public static T getInstance<T>() where T: class {
		return default(T);
	}

	public static void setInterface<T>(T instance) where T: class {	
	}
}
